2019-06-07 10:06:00,345 ERROR: Exception on /index [GET] [in c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\routes.py", line 37, in index
    prev_url=prev_url)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\templates\index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2019-06-07 10:06:03,180 ERROR: Exception on /user/Badri [GET] [in c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\routes.py", line 105, in user
    next_url=next_url, prev_url=prev_url)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\templates\user.html", line 24, in block "content"
    {% include '_post.html' %}
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\badri\desktop\ps1 work\ps1_work\assignment\assign2\flasktut\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2019-06-07 10:10:47,964 INFO: Microblog startup [in C:\Users\Badri\Desktop\PS1 Work\PS1_Work\Assignment\assign2\flaskTut\app\__init__.py:43]
